config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "posts#index"
  resources :posts do
    member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

	mount_uploader :photo, PhotoUploader

	acts_as_votable

	def self.search(query)
  		where("title like ?", "%#{query}%")
  		where("content like ?", "%#{query}%")
	end

	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create

		@post = Post.find(params[:post_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.post_id = @post.id
		#@comments = Comment.all

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :authenticate_user!, except: [:index, :show]
   before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

	def index 
		if params[:search]
    		@posts = Post.search(params[:search]).order("created_at DESC")
  		else
    		@posts = Post.all
  		end
	end

	def new	
		@post = current_user.posts.build	
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def show
		@comments = Comment.where(post_id: @post)
		@random_post = Post.where.not(id: @post).order("RANDOM()").first
	end

	def edit

	end

	def upvote
		@post.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@post.downvote_by current_user
		redirect_to :back
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end	
	end


	private
		def find_post
			@post=Post.find(params[:id])
		end

		def post_params
      		params.require(:post).permit(:title, :photo, :content)
    	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :content, label: "Reply to post"
	= f.button :submit, class: 'btn btn-default'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pinterest
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %a.navbar-brand{:href => posts_path} Pinterest
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => new_post_path}
                New Post
                %span.sr-only (current) 
          %form.navbar-form.navbar-left
            = form_tag(posts_path, :method => "get", id: "search-form") do
              = text_field_tag :search, params[:search], placeholder: "Search"
              = submit_tag "Search", :name => nil
          %ul.nav.navbar-nav.navbar-right
            -if !user_signed_in?
              %li
                = link_to "Sign In", new_user_session_path
              %li  
                = link_to "Sign Up", new_user_registration_path
            -if user_signed_in?
              %li
                = link_to "Account", edit_user_registration_path
              %li
                = link_to "Log Out", destroy_user_session_path, method: :delete, class:'btn'
        / /.navbar-collapse
      / /.container-fluid
    .wrapper
      = yield

app/views/posts/_form.html.haml
= simple_form_for(@post) do |f|
  = f.error_notification

  .form-inputs
    = f.input :photo
    = f.input :title
    = f.input :content

  .form-actions
    = f.button :submit

app/views/posts/edit.html.haml
.col-md-6.col-md-offset-3
	%h1 Edit post

	= render 'form'

	= link_to 'Show', @post
	\|
	= link_to 'Back', posts_path

app/views/posts/index.html.haml
- @posts.each do |post|
  .post
    .image
      = image_tag post.photo, size: '300x300'
    .panel.panel-success
      .panel-heading 
        = post.title
      .panel-footer 
        = post.content    
    = link_to "Edit", edit_post_path(post.id), class: 'btn btn-default'
    = link_to 'Show', post_path(post.id),  class: 'btn btn-default'
    = link_to 'Destroy', post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default'

app/views/posts/new.html.haml
.col-md-6.col-md-offset-3
	%h1 New post

	= render 'form'

	= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
.wrapper
  .left-side
    .panel.panel-default
      .panel-body
        .panel-photo
          =image_tag @post.photo
        .post-panel
          = link_to "like", like_post_path(@post), method: :get
          = @post.get_upvotes.size
          = link_to "dislike", dislike_post_path(@post), method: :get
          = @post.get_downvotes.size
          -if user_signed_in?
            -if @post.user_id == current_user.id
              = link_to 'Edit', edit_post_path(@post)
              \|
              = link_to 'Back', posts_path
        %h3= @post.title
        = @post.content
  .right-side
    .comments
      .panel.panel-default
        .panel-heading
          Comments
        .panel-body
          -@comments.each do |comment|
            .author
              Posted by
              =comment.user.email
            %p=comment.content
            %hr
          =render 'comments/form'
    .random-post
      .panel.panel-default
        .panel-body
          = link_to (image_tag @random_post.photo), @random_post
        .panel-footer
          =@random_post.title